apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - gf-auth.yaml
  - gf-oauth-client-data.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 81.5.0
    releaseName: kube-prometheus-stack
    namespace: prometheus-stack
    valuesFile: values.yaml