apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly-system

resources:
  - ns.yaml
  - dragonfly-db.yaml

helmCharts:
  - name: dragonfly-operator
    repo: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
    version: "v1.3.0"
    releaseName: dragonfly-operator
    namespace: dragonfly-system
    valuesFile: values.yaml
