apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-secrets-operator

resources:
  - ns.yaml

helmCharts:
  - name: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    releaseName: vault-secrets-operator
    namespace: vault-secrets-operator
    version: "1.2.0"
    valuesFile: values.yaml