apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-agent-injector

resources:
  - ns.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    namespace: vault-agent-injector
    version: "0.31.0"
    valuesFile: values.yaml