apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: traefik-external
spec:
  dnsNames:
    - "*.sudoceo.com"
    - sudoceo.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: gateway-cert
  usages:
    - digital signature
    - key encipherment